# DukeCook Home Assistant Integration
# Sensors and automations for meal planning
# URL: https://cook.trevorduke.com

rest:
  - resource: "http://192.168.1.131:8080/api/ha/tonight"
    scan_interval: 300
    sensor:
      - name: "DukeCook Tonight"
        unique_id: dukecook_tonight
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - planned
          - recipe_title
          - cuisine
          - total_time_min
          - recipe_id

  - resource: "http://192.168.1.131:8080/api/ha/week-summary"
    scan_interval: 600
    sensor:
      - name: "DukeCook Week"
        unique_id: dukecook_week
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - planned_count
          - cooked_count
          - remaining
          - schedule

  - resource: "http://192.168.1.131:8080/api/ha/shopping-count"
    scan_interval: 120
    sensor:
      - name: "DukeCook Shopping"
        unique_id: dukecook_shopping
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - total
          - checked
          - remaining

  - resource: "http://192.168.1.131:8080/api/ha/stats"
    scan_interval: 3600
    sensor:
      - name: "DukeCook Stats"
        unique_id: dukecook_stats
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - total_recipes
          - cooked_this_week
          - total_meals_cooked

automation:
  - id: dukecook_dinner_reminder
    alias: "DukeCook: Dinner Reminder"
    trigger:
      - platform: time
        at: "16:00:00"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.dukecook_tonight
            state: "Nothing planned"
    action:
      - action: notify.mobile_app_trevors_iphone
        data:
          title: "🍳 Tonight's Dinner"
          message: "{{ states('sensor.dukecook_tonight') }}"
          data:
            url: "https://cook.trevorduke.com"

  - id: dukecook_no_dinner_planned
    alias: "DukeCook: No Dinner Planned"
    trigger:
      - platform: time
        at: "14:00:00"
    condition:
      - condition: state
        entity_id: sensor.dukecook_tonight
        state: "Nothing planned"
    action:
      - action: notify.mobile_app_trevors_iphone
        data:
          title: "📅 No Dinner Planned Tonight"
          message: "Open DukeCook to plan or start swiping!"
          data:
            url: "https://cook.trevorduke.com/swipe"

  - id: dukecook_shopping_reminder
    alias: "DukeCook: Weekly Shopping Reminder"
    trigger:
      - platform: time
        at: "10:00:00"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - action: notify.mobile_app_trevors_iphone
        data:
          title: "🛒 Shopping List Ready"
          message: "{{ states('sensor.dukecook_shopping') }}"
          data:
            url: "https://cook.trevorduke.com/shopping"
